name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, labeled, ready_for_review, synchronize]

jobs:
  label_check:
    runs-on: ubuntu-latest
    steps:
    - name: labels
      if: ${{ github.event.label.name != 'ok-to-test' }}
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('missing ok-to-test label')

  unit_tests:
    needs: label_check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test ./...