name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  label_check:
    if: ${{ github.event.label.name != 'ok-to-test' }}
    uses: actions/github-script@v3
    with:
      script: |
          core.setFailed('missing ok-to-test label')
  unit_tests:
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test ./...