name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, labeled, ready_for_review, synchronize]

  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: check-labels
      if: github.event_name == 'pull_request' && "!contains(github.event.pull_request.labels.*.name, 'ok-to-test')"
      uses: actions/github-script@v3
      with:
        script: |
            core.setFailed('missing ok-to-test label')

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test ./...